export enum ProductProvider {
	STARTECH = "STARTECH",
	RYANS = "RYANS",
	TECHLAND = "TECHLAND",
	COMPUTER_VILLAGE = "COMPUTER_VILLAGE",
	TECH_MARVELS = "TECH_MARVELS",
	VERTECH = "VERTECH",
	APPLE_GADGETS = "APPLE_GADGETS",
}
