name: Deploy PriceLens Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.HOST_IP}} >> ~/.ssh/known_hosts

      - name: Deploy to VPS via SSH
        run: |
          ssh ${{secrets.SSH_USER}}@${{secrets.HOST_IP}}<<'EOF'
            set -e # Exit on error
            mkdir -p ${{secrets.PROJECT_PATH}}
            cd ${{secrets.PROJECT_PATH}}

            if [ -d ".git" ]; then
              git pull origin HEAD
            else
              git init
              git remote add origin https://github.com/${{ github.repository }}
              git branch -m main
              git pull origin main
            fi

            cat > .env << 'ENVEOF'
          ${{ secrets.ENV_VALUES }}
          ENVEOF

            # Install packages
            ~/.bun/bin/bun i

            if pm2 list | grep -Eq 'pricelens_backend'; then
              pm2 restart pricelens_backend --update-env
            else
              pm2 start ~/.bun/bin/bun --name pricelens_backend -- run index.ts
            fi
            pm2 save
          EOF

      - name: Clean Up SSH Key
        run: rm -rf ~/.ssh/id_rsa
